### ISSUE TITLE
Config vars

### ISSUE THREAD

**Issue by chrisc93** [BlueWallet/GroundControl#2]
Is there a guide to creating the APN cert? Do you need to have an apple developer account to run this?
Also, how do you get the FCM key from firebase?

**Comment by Overtorment** [comment]
heres a pretty good guide I used https://dev.to/jakubkoci/react-native-push-notifications-313i
yes, you need apple developer account.

**Comment by chrisc93** [comment]
Thanks for that guide! It looks pretty simple to remove the APNs parts too.
