### ISSUE TITLE
[Prod.] Sender is probably broken

### ISSUE THREAD

**Issue by AbdelrahmanManz** [BlueWallet/GroundControl#248]
Hey, thanks for your efforts on this project, I was testing the swagger enqueue token endpoint with a token from the app, and it may have broken the sender process, as the queue size was "0", and right after it became congested, with more and more notifications, also the "sent_24h" property is decreasing over time for some reason, unless it's a quota or something and the name is tricky, and this is just a bad coincidence, I thought I'd open this issue

![image](https://user-images.githubusercontent.com/24511018/210024959-a6370197-8673-4035-82cd-4efab6292e97.png)

1 min after:
![image](https://user-images.githubusercontent.com/24511018/210025005-afb416f2-69f0-45f8-baa2-9a0021366f9d.png)

**Comment by Overtorment** [comment]
ah ok i was wondering what was going on. i fixed this case in latest commit
