### ISSUE TITLE
Installation Guide - GroundControl 

### ISSUE THREAD

**Issue by RobN007** [BlueWallet/GroundControl#272]
Hello!

I'm excited about this project and would love to set up my own GroundControl for sending myself notifications. However, I'm not very experienced with computers, so I rely heavily on clear instructions.

Firstly, is it possible to install this on my Synology Disk Station? I've heard about something called Docker Desktop, would that help?

If not, I'm open to trying Heroku, but I'm a bit nervous about it since I'm not very familiar with your setup instructions.

I'm sorry for any inconvenience, and I really appreciate any help you can offer!

Cheers

**Comment by Overtorment** [comment]
Hello, the biggest problem is actually not installing it, but getting push certificates from Apple & Google.

So this project is opensourced mostly for the developers who maintain BW forks (sometimes for altcoins) and who are experienced developers.

**Comment by RobN007** [comment]
Thank you! So this is probably not for me unfortunately.What is your statement about using the BlueWallet integrated Notification function, I’m wondering if I’m loosing my privacy and the wallet I want to get notifications for can be linked directly to me as a person. Is this a concern I should have ?Thanks in advance Am 23.03.2024 um 17:13 schrieb Overtorment ***@***.***>:﻿
Hello, the biggest problem is actually not installing it, but getting push certificates from Apple & Google.
So this project is opensourced mostly for the developers who maintain BW forks (sometimes for altcoins) and who are experienced developers.

**Comment by Overtorment** [comment]
Yes, you are losing privacy, push notifications server knows which addresses you track to get notified about.
