### ISSUE TITLE
Incomplete build instructions

### ISSUE THREAD

**Issue by cbrunnkvist** [BlueWallet/GroundControl#280]
How about writing down the exact steps you need to take in order to build it, let's say also build a docker image? There's some comments about extracting certificates or something but it doesn't say how it relates to setting up & running your own node really.

**Comment by Lsifuentez74** [comment]
Help me

**Comment by Overtorment** [comment]
[How to install and run](https://github.com/BlueWallet/GroundControl#installation)

wrapping in docker, k8s, or whatever, is up to you
