### ISSUE TITLE
Please explain who would use this

### ISSUE THREAD

**Issue by xanoni** [BlueWallet/GroundControl#89]
I'm confused about what this repository is and how I would use this or who would use this. I see that `GroundControlToMajorTom` talks to both Apple (`https://api.push.apple.com`) and Google (`https://fcm.googleapis.com`) push servers.

Thus, it seems that this is the infrastructure component that tells the Apple and Google servers what devices to ping if something relevant to the user's wallets happens.

However, I doubt that I can just run this to ping a device that runs the official build of BlueWallet? I assume Apple/Google would want to see some certificate to make sure that only the BlueWallet team can ping devices? How would I populate the stuff below?
```
FCM_SERVER_KEY hex encoded
APNS_PEM hex encoded
APNS_TOPIC for example io.bluewallet.bluewallet
```

**Comment by Overtorment** [comment]
this is generic push notification service. 
it can be used by any of 400+ forks of bluewallet (some fork bw to work with other utxo-based coins).

and yes, unfortunately its not trivial to use this for a regular user. in perfect world user would install this on his own raspberry pi along (umbrel/mynodebtc/raspiblitz etc) for maximum self sovereignty.
but in real world user would probably also have to compile BW himself, change bundle id, and issue his own certficates as described here: https://dev.to/jakubkoci/react-native-push-notifications-313i

**Comment by xanoni** [comment]
> but in real world user would probably also have to compile BW himself, change bundle id, and issue his own certficates as described here:

@Overtorment: This is all fine, but the problem is that the UI from the Apple App Store and the Google Play Store Builds suggests that this is something that the user can easily do and is encouraged to do … see for example what it looks like on iOS:

![BDD2CFAE-4ED5-4E03-BE0A-91FF849A9AAB](https://user-images.githubusercontent.com/77220130/127219061-8322c4b3-2555-4188-9b76-4be347c39ea2.jpeg)

**Comment by Overtorment** [comment]
yeah, this want very well thought through...
anyway, keeping it as is for now

**Comment by xanoni** [comment]
> yeah, this want very well thought through...
> 
> anyway, keeping it as is for now

Ok, I'll stop asking, guess there are reasons 😂

**Comment by Overtorment** [comment]
typo, this WASNT very well thought through

**Comment by xanoni** [comment]
I got that. I just didn't understand why you think the GUI should not warn users. I researched this software only to find out that I can't use it with the wallet build that told me about it ...

**Comment by bota87** [comment]
> I got that. I just didn't understand why you think the GUI should not warn users. I researched this software only to find out that I can't use it with the wallet build that told me about it ...

+1 to explain better that self-host ground control isn't enought
